=== Aleamoca/AE2-xml-dtd-xsd-lenguajes/XSD_biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
Esquema que marca la estructura de una biblioteca
        </xs:documentation>
    </xs:annotation>
    <!-- El nodo raÃ­z se llama biblioteca-->
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <!-- El elemento libros-->
                <xs:element name="libros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="index"></xs:element>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="Capitulos"></xs:element>
                                        <xs:element name="sinopsis" type="xs:string"></xs:element>
                                        <xs:element name="num_paginas" type="xs:integer"></xs:element>
                                        <xs:sequence>
                                            <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="titulo" type="xs:string"></xs:element>
                                                        <xs:element name="contenido" type="xs:string"></xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="num_paginas" type="xs:string" use="required"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:string" use="required"/>
                        <xs:attribute name="tipo_clase" type="xs:string" use="required"/>
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="novela"></xs:enumeration>
                                    <xs:enumeration value="infantil"></xs:enumeration>
                                    <xs:enumeration value="didactico"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<!-- El elemento revistas-->
<xs:element name="revistas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="revista" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo" type="xs:string"/>
                        <xs:element name="numero" type="xs:integer"/>
                        <xs:element name="indice"/>
                        <xs:element name="secciones">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="seccion" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="numero_paginas" type="xs:integer" use="required"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                            <xs:element name="contenido">
                                                <xs:complexType>
                                                    <xs:attribute name="enlace" type="xs:anyURI" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:attribute name="tipo" type="xs:string" use="required"/>
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="informatica"></xs:enumeration>
                                                        <xs:enumeration value="corazon"></xs:enumeration>
                                                        <xs:enumeration value="coches"></xs:enumeration>
                                                        <xs:enumeration value="investigacion"></xs:enumeration>
                                                        <xs:enumeration value="otras"></xs:enumeration>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

 <!-- El elemento periodicos-->
<xs:element name="periodicos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="periodico" minOccurs="1" maxOccurs="2">
                <xs:complexType>
                    <xs:attribute name="Id" type="xs:string" use="required"/>
                    <xs:attribute name="tipo_clase" type="xs:string" use="required"/>
                    <xs:attribute name="fecha_publicacion" type="xs:date" use="required"/>
                </xs:complexType>
            </xs:element>
                    <xs:element name="index">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="sections">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="section" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="articulos" minOccurs="1" maxOccurs="unbounded">
                                                            <xs:complexType>
                                                                <xs:attribute name="autor" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                        </xs:element>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="informacion" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                </xs:sequence>
                                                                <xs:attribute name="tipo" type="xs:string" use="required"/>
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:enumeration value="economica"></xs:enumeration>
                                                                            <xs:enumeration value="opinion"></xs:enumeration>
                                                                            <xs:enumeration value="deportes"></xs:enumeration>
                                                                            <xs:enumeration value="nacional"></xs:enumeration>
                                                                            <xs:enumeration value="internacional"></xs:enumeration>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:attribute>  
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Aleamoca/AE2-xml-dtd-xsd-lenguajes/AE-2. XML, DTD y XSD.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation= "XSD_biblioteca.xsd">
    <libros>
        <libro Id= "L1010" tipo_clase= "novela">
            <index>
                <titulo>Obra Maestra</titulo>
                <capitulos>
                    <capitulo num_pag="50">
                        <titulo>capitulo 1</titulo>
                        <contenido enlace="https://www.bbc.com/mundo/noticias-62419975"/>
                    </capitulo>
                    <capitulo num_pag="45">
                        <titulo>capitulo 2</titulo>
                        <contenido enlace="https://www.bbc.com/mundo/noticias-62419975"/>
                    </capitulo>
                    <capitulo num_pag="65">
                        <titulo>capitulo 3</titulo>
                        <contenido enlace="https://www.bbc.com/mundo/noticias-62419975"/>
                    </capitulo>
                    <sinopsis>"La increíble historia de la desaparición en España de una escultura de 38 
                                toneladas que aún hoy nadie puede explicar"</sinopsis>
                    <num_paginas>150</num_paginas>
                </capitulos>
            </index>
        </libro>
        <libro Id="L1112" tipo_clase="infantil">
            <index>
                <titulo>Un cuento para cada letra</titulo>
                <capitulos>
                    <capitulo num_paginas="10">
                        <titulo>Capítulo 1</titulo>
                        <contenido enlace="https://www.orientacionandujar.es/2017/09/23/coleccion-cuentos-letra-del-abecedario/"/>
                    </capitulo>
                    <capitulo num_paginas="10">
                        <titulo>Capítulo 2</titulo>
                        <contenido enlace="https://www.orientacionandujar.es/2017/09/23/coleccion-cuentos-letra-del-abecedario/"/>
                    </capitulo>
                    <capitulo num_paginas="10">
                        <titulo>Capítulo 3</titulo>
                        <contenido enlace="https://www.orientacionandujar.es/2017/09/23/coleccion-cuentos-letra-del-abecedario/"/>
                    </capitulo>
                </capitulos>
                <sinopsis>"Este recopilatorio de 29 cuentos, uno por cada letra del abecedario, 
                           se ha ideado para que los niños que están aprendiendo a leer y escribir 
                           distingan las grafías y sonidos de cada letra y aprendan a reconocerlas"
                </sinopsis>
                <num_paginas>30</num_paginas>
            </index>
        </libro>
        <libro Id="L0012" tipo_clase="didactico">
            <libro Id= "L1010" tipo_clase= "novela">
                <index>
                    <titulo>Lo que aprendí mientras te portabas mal</titulo>
                    <capitulos>
                        <capitulo num_paginas="60">
                            <titulo>Capítulo 1</titulo>
                            <contenido enlace="https://www.educaciontrespuntocero.com/libros/los-mejores-libros-para-docentes/#Lo-que-aprendi-mientras-te-portabas-mal"/>
                        </capitulo>
                        <capitulo num_paginas="55">
                            <titulo>Capítulo 2</titulo>
                            <contenido enlace="https://www.educaciontrespuntocero.com/libros/los-mejores-libros-para-docentes/#Lo-que-aprendi-mientras-te-portabas-mal"/>
                        </capitulo>
                        <capitulo num_paginas="55">
                            <titulo>Capítulo 3</titulo>
                            <contenido enlace="https://www.educaciontrespuntocero.com/libros/los-mejores-libros-para-docentes/#Lo-que-aprendi-mientras-te-portabas-mal"/>
                        </capitulo>
                    </capitulos>
                    <sinopsis>"El cómo cambiar los castigos y la silla de pensar por valor y 
                    pertenencia en un espacio seguro de aprendizaje."</sinopsis>
                    <num_paginas>120</num_paginas>
                </index>
            </libro>
        </libro>
    </libros>
    <revistas>
        <revista Id="R2356" tipo_clase="informática">
            <titulo>Computer Hoy</titulo>
            <numero>678</numero>
                <indice>
                    <secciones>
                        <seccion tipo="actualidad" numero_paginas="20">
                            <contenido enlace="https://computerhoy.com/"/>
                        </seccion>
                        <seccion tipo="practico" numero_paginas="25">
                            <contenido enlace="https://computerhoy.com/"/>
                        </seccion>
                    </secciones>
                </indice>
        </revista>
        <revista Id="R2351" tipo_clase="corazón">
            <titulo>Hola</titulo>
            <numero>1023</numero>
                <indice>
                    <secciones>
                        <seccion tipo="corazon" numero_paginas="20">
                            <contenido enlace="https://www.hola.com/"/>
                        </seccion>
                        <seccion tipo="horoscopo" numero_paginas="10">
                            <contenido enlace="https://www.hola.com"/>
                        </seccion>
                    </secciones>
                </indice>
        </revista>
        <revista Id="R2365" tipo_clase="coches">
            <titulo>Motor Pasión</titulo>
            <numero>2000</numero>
                <indice>
                    <secciones>
                        <seccion tipo="comparativas" numero_paginas="20">
                            <contenido enlace="https://www.motorpasion.com/"/>
                        </seccion>
                        <seccion tipo="electricos" numero_paginas="10">
                            <contenido enlace="https://www.motorpasion.com/"/>
                        </seccion>
                    </secciones>
                </indice>
        </revista>
        <revista Id="R2345" tipo_clase="investigación">
            <titulo>Phys.org</titulo>
            <numero>200</numero>
                <indice>
                    <secciones>
                        <seccion tipo="nanotecnologia" numero_paginas="20">
                            <contenido enlace="https://phys.org/"/>
                        </seccion>
                        <seccion tipo="neurociencia" numero_paginas="30">
                            <contenido enlace="https://phys.org/"/>
                        </seccion>
                    </secciones>
                </indice>
        </revista>
        <revista Id="R2346" tipo_clase="otras">
            <titulo>Time</titulo>
            <numero>4500</numero>
                <indice>
                    <secciones>
                        <seccion tipo="politica" numero_paginas="20">
                            <contenido enlace="https://time.com/"/>
                        </seccion>
                        <seccion tipo="negocios" numero_paginas="20">
                            <contenido enlace="https://time.com/"/>
                        </seccion>
                        <seccion tipo="salud" numero_paginas="20">
                            <contenido enlace="https://time.com/"/>
                        </seccion>
                    </secciones>
                 </indice>
        </revista>
    </revistas>
    <periodicos>
        <periodico Id="P1002" tipo_clase="nacional" fecha_publicacion="08/05/2023">
        </periodico>
        <periodico Id="P1003" tipo_clase="internacional" fecha_publicacion="08/05/2023">
        </periodico>
            <index>
                <secciones>
                    <seccion tipo= "economica">
                        <articulos autor="Josep Fontana"></articulos>
                        <contenido informacion= "toda la informacion que nos aprote en la noticia"></contenido>
                    </seccion>
                    <seccion tipo= "opinion">
                        <articulos autor="Jose Carlos Diez"></articulos>
                        <contenido informacion= "toda la informacion que nos aprote en la noticia"></contenido>
                    </seccion>
                    <seccion tipo= "deportes">
                        <articulos autor="Ramón de España"></articulos>
                        <contenido informacion= "toda la informacion que nos aprote en la noticia"></contenido>
                    </seccion>
                    <seccion tipo= "nacional">
                        <articulos autor="Manuel Cruz"></articulos>
                        <contenido informacion= "toda la informacion que nos aprote en la noticia"></contenido>
                    </seccion>
                    <seccion tipo= "internacional">
                        <articulos autor="Josep Oliver"></articulos>
                        <contenido informacion= "toda la informacion que nos aprote en la noticia"></contenido>
                    </seccion>
                </secciones>
            </index>
    </periodicos>
</biblioteca>
